-- Create the DB table
CREATE TABLE IF NOT EXISTS swarm (
    name TEXT,
    jobid INTEGER PRIMARY KEY,
    hf_home TEXT,
    model TEXT,
    revision TEXT,
    replicas INT,
    gpus_per_replica INT,
    gpus_per_node INT,
    replicas_per_node INT,
    nodes INT,
    cpus_per_task INT,
    requires_ray BOOLEAN,
    mem_per_cpu TEXT,
    partition TEXT,
    account TEXT,
    vllm_image TEXT,
    nginx_image TEXT,
    lb_wait INTEGER,
    lb_port INTEGER,
    home_directory TEXT,
    log_directory TEXT,
    max_concurrent_requests INTEGER,
    poll_interval INTEGER,
    template_path TEXT,
    nginx_template_path TEXT,
    vllm_args TEXT,
    vllm_port INTEGER,
    ray_port INTEGER,
    ray_dashboard_port INTEGER,
    venv_path TEXT,
    time_limit DATETIME,
    exclude_nodes TEXT,
    node_list TEXT,
    mail_user TEXT,
    lb_jobid INTEGER,
    lb_node TEXT,
    endpoint TEXT,
    delete_on_exit BOOLEAN,
    driver_cpus_per_task INTEGER,
    driver_mem TEXT,
    driver_threads_per_core INTEGER,
    driver_wall_time TIME,
    driver_enable_proxy_buffering BOOLEAN,
    driver_nginx_timeout STRING
);