# Copyright 2025 iGenius S.p.A
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""baseline swarm db

Revision ID: 810a9198a632
Revises:
Create Date: 2025-10-29 16:54:25.894931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "810a9198a632"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swarm",
        "deployment_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
    )
    op.alter_column(
        "swarm", "swarm", existing_type=sa.TEXT(), type_=sa.JSON(), nullable=False
    )
    op.alter_column(
        "swarm", "cfg", existing_type=sa.TEXT(), type_=sa.JSON(), nullable=False
    )
    op.alter_column(
        "swarm",
        "serving_handle",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "swarm",
        "creation_dt",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swarm",
        "creation_dt",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "swarm",
        "serving_handle",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "swarm", "cfg", existing_type=sa.JSON(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "swarm", "swarm", existing_type=sa.JSON(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "swarm",
        "deployment_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###
