"""baseline swarm db

Revision ID: 810a9198a632
Revises:
Create Date: 2025-10-29 16:54:25.894931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "810a9198a632"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swarm",
        "deployment_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
    )
    op.alter_column(
        "swarm", "swarm", existing_type=sa.TEXT(), type_=sa.JSON(), nullable=False
    )
    op.alter_column(
        "swarm", "cfg", existing_type=sa.TEXT(), type_=sa.JSON(), nullable=False
    )
    op.alter_column(
        "swarm",
        "serving_handle",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "swarm",
        "creation_dt",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swarm",
        "creation_dt",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "swarm",
        "serving_handle",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "swarm", "cfg", existing_type=sa.JSON(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "swarm", "swarm", existing_type=sa.JSON(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "swarm",
        "deployment_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###
