# SPDX-FileCopyrightText: 2025-2026 Domyn
# SPDX-License-Identifier: Apache-2.0

"""Behaviour contract for the pandas and Arrow execution engines.

These tests characterize existing behaviour so the consolidation in
`jobs/execution/pipeline.py` can be proven to change nothing. They are written
against the public `run_job_unified` entry point rather than the private engine
functions, so they survive the refactor unchanged.

Do not edit this file to make a refactor pass. A failure here is a behaviour
change, which is the finding.
"""

from typing import Any

import pandas as pd
import pyarrow as pa
import pytest

from domyn_swarm.jobs import SwarmJob
from domyn_swarm.jobs.api.base import OutputJoinMode
from domyn_swarm.jobs.cli.run import run_job_unified


class CharacterizationJob(SwarmJob):
    """Deterministic job: output depends only on the input item."""

    max_concurrency = 2
    retries = 1
    timeout = 10
    output_mode = OutputJoinMode.APPEND

    def __init__(self, **kwargs):
        kwargs.setdefault("endpoint", "http://dummy-endpoint")
        kwargs.setdefault("model", "dummy-model")
        kwargs.setdefault("input_column_name", "messages")
        kwargs.setdefault("output_cols", "output")
        super().__init__(**kwargs)

    async def transform_items(self, items: list):
        return [f"out-{i}" for i in items]


def _normalize(result: Any, id_col: str) -> tuple[str, list[tuple]]:
    """Reduce any engine's return value to a comparable, order-independent form.

    Args:
        result: Whatever the engine returned (pandas DataFrame or Arrow table).
        id_col: Column holding stable row ids.

    Returns:
        A tuple of ``(id_dtype, rows)``: the id column's dtype name, and rows as
        ``(id, output)`` tuples sorted by id. The dtype check is restricted to
        the id column on purpose: pandas and Arrow legitimately differ on other
        columns' dtypes (e.g. object vs. string for "output"), but the id
        column surviving the round trip with the same type, on both engines,
        is exactly the property this consolidation must not let drift.
    """
    df = result.to_pandas() if isinstance(result, pa.Table) else result
    pairs = list(zip(df[id_col].tolist(), df["output"].tolist(), strict=True))
    return str(df[id_col].dtype), sorted(pairs, key=lambda row: row[0])


# (engine_kwargs, label) -- the two routes under test.
ENGINES = [
    pytest.param({"runner": "pandas"}, id="pandas"),
    pytest.param({"runner": "arrow"}, id="arrow"),
]


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_kwargs", ENGINES)
@pytest.mark.parametrize("nshards,shard_mode", [(1, "id"), (4, "id"), (4, "index")])
@pytest.mark.parametrize("global_resume", [False, True])
async def test_engines_agree_across_the_option_matrix(
    tmp_path, engine_kwargs, nshards, shard_mode, global_resume
):
    """Both engines produce identical rows for every valid option combination.

    Sharded execution requires checkpointing, so `checkpointing=False` is only
    exercised with `nshards == 1` (see the dedicated test below).
    """
    df = pd.DataFrame({"doc_id": [10, 11, 12, 13, 14], "messages": [1, 2, 3, 4, 5]})

    result = await run_job_unified(
        lambda: CharacterizationJob(id_column_name="doc_id"),
        df,
        input_col="messages",
        output_cols=["output"],
        store_uri=f"file://{tmp_path / 'out.parquet'}",
        nshards=nshards,
        shard_mode=shard_mode,
        global_resume=global_resume,
        checkpointing=True,
        **engine_kwargs,
    )

    assert _normalize(result, "doc_id") == (
        "int64",
        [
            (10, "out-1"),
            (11, "out-2"),
            (12, "out-3"),
            (13, "out-4"),
            (14, "out-5"),
        ],
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_kwargs", ENGINES)
async def test_engines_agree_without_checkpointing(tmp_path, engine_kwargs):
    """Single-shard execution with checkpointing disabled."""
    df = pd.DataFrame({"doc_id": [1, 2], "messages": [7, 8]})

    result = await run_job_unified(
        lambda: CharacterizationJob(id_column_name="doc_id"),
        df,
        input_col="messages",
        output_cols=["output"],
        store_uri=None,
        nshards=1,
        checkpointing=False,
        **engine_kwargs,
    )

    assert _normalize(result, "doc_id") == ("int64", [(1, "out-7"), (2, "out-8")])


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_kwargs", ENGINES)
async def test_engines_agree_without_checkpointing_empty_input(tmp_path, engine_kwargs):
    """Single-shard execution with checkpointing disabled, on a zero-row input.

    `InMemoryStore.finalize()` (used whenever `checkpointing=False`) used to fall
    back to `pd.DataFrame().set_index(self.id_col)` when nothing was ever
    flushed, and an empty `pd.DataFrame()` has no columns to index by -- so the
    pandas engine raised `KeyError` on an empty input while the Arrow engine
    returned an empty result. This pins the fixed behaviour: no rows, no crash,
    and the id column's (now merely "object", since there is no data anywhere to
    infer a real dtype from) type still agrees between engines.

    The input is sliced from a non-empty, int64-typed frame rather than built
    from empty Python lists, so this isolates the id-column-on-empty-input
    behaviour from pandas' unrelated empty-list dtype inference (`[]` infers as
    float64, not int64).

    This doesn't use `_normalize`: with zero rows ever processed, neither
    engine materializes an "output" column at all (there is nothing to derive
    it from), so `_normalize`'s `df["output"]` lookup would raise on both
    engines -- itself a real, if narrow, point of agreement worth pinning
    directly rather than papering over inside the shared helper.
    """
    df = pd.DataFrame({"doc_id": [1, 2], "messages": [7, 8]}).iloc[0:0]

    result = await run_job_unified(
        lambda: CharacterizationJob(id_column_name="doc_id"),
        df,
        input_col="messages",
        output_cols=["output"],
        store_uri=None,
        nshards=1,
        checkpointing=False,
        **engine_kwargs,
    )

    df_result = result.to_pandas() if isinstance(result, pa.Table) else result
    assert len(df_result) == 0
    assert "output" not in df_result.columns
    assert str(df_result["doc_id"].dtype) == "object"


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_kwargs", ENGINES)
async def test_sharding_without_checkpointing_is_rejected(tmp_path, engine_kwargs):
    """Sharded execution requires checkpointing, on both engines."""
    df = pd.DataFrame({"doc_id": [1, 2], "messages": [7, 8]})

    with pytest.raises(ValueError, match="requires checkpointing"):
        await run_job_unified(
            lambda: CharacterizationJob(id_column_name="doc_id"),
            df,
            input_col="messages",
            output_cols=["output"],
            store_uri=f"file://{tmp_path / 'out.parquet'}",
            nshards=4,
            checkpointing=False,
            **engine_kwargs,
        )


@pytest.mark.asyncio
async def test_checkpoints_are_portable_between_engines(tmp_path):
    """A job checkpointed by one engine resumes correctly under the other.

    `ParquetShardStore` (pandas engine) and `ArrowShardStore` (Arrow engine)
    implement the same on-disk contract. This locks that property, so a change
    to either store breaks a test rather than someone's resumed job.
    """
    store_uri = f"file://{tmp_path / 'out.parquet'}"
    df = pd.DataFrame({"doc_id": [1, 2, 3, 4], "messages": [1, 2, 3, 4]})

    # First pass under the pandas engine.
    await run_job_unified(
        lambda: CharacterizationJob(id_column_name="doc_id"),
        df,
        input_col="messages",
        output_cols=["output"],
        store_uri=store_uri,
        nshards=2,
        checkpointing=True,
        global_resume=True,
        runner="pandas",
    )

    # Resume under the Arrow engine. Any item it re-processes would raise.
    class ExplodingJob(CharacterizationJob):
        async def transform_items(self, items: list):
            raise AssertionError(f"re-processed already-done items: {items}")

    result = await run_job_unified(
        lambda: ExplodingJob(id_column_name="doc_id"),
        df,
        input_col="messages",
        output_cols=["output"],
        store_uri=store_uri,
        nshards=2,
        checkpointing=True,
        global_resume=True,
        runner="arrow",
    )

    assert _normalize(result, "doc_id") == (
        "int64",
        [
            (1, "out-1"),
            (2, "out-2"),
            (3, "out-3"),
            (4, "out-4"),
        ],
    )
