model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
name: deepseek-r1
revision: main
gpus_per_replica: 8
replicas: 1
args: "--dtype bfloat16 --gpu-memory-utilization 0.95 --max-model-len 8192 --reasoning-parser deepseek_r1 --max-num-seqs 128"
wait_endpoint_s: 3600
image: "/path/to/vllm.sif"
env:
  HF_HOME: /path/to/shared_hf_cache
backend:
  type: slurm
  partition: partition_name
  account: account_name
  qos: qos_name
  endpoint:
    port: 9001
    cpus_per_task: 4
    wall_time: "36:00:00"
    nginx_image: "/path/to/nginx.sif"
