model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
revision: main
gpus_per_replica: 8
replicas: 1
args: "--dtype bfloat16 --gpu-memory-utilization 0.95 --max-model-len 8192 --reasoning-parser deepseek_r1 --max-num-seqs 128"
wait_endpoint_s: 3600
image: "/leonardo_work/iGen_train/fdambro1/images/vllm_0.10.1.1.sif"
env:
  HF_HOME: /leonardo_scratch/fast/iGen_train/shared_hf_cache/
backend:
  type: slurm
  partition: boost_usr_prod
  account: igen_train
  qos: qos_llm_min
  endpoint:
    port: 9001
    cpus_per_task: 4
    wall_time: "36:00:00"
