name: domyn-small
model: "/leonardo_scratch/fast/iGen_train/nvidia_checkpoints/Domyn-Small-16k-sft-acereason-balanced-hf"
replicas: 4
gpus_per_replica: 4
image: "/leonardo_work/iGen_train/fdambro1/images/vllm_0.10.1.1.sif"
args: "--max-model-len 16384"
backend:
  type: slurm
  partition: boost_usr_prod
  account: iGen_train
  qos: qos_llm_min
  endpoint:
    nginx_image: "/leonardo_work/iGen_train/fdambro1/images/nginx-dask.sif"
    wall_time: "05:00:00"
    nginx_timeout: "8h"
