model: Qwen/Qwen3-235B-A22B
name: qwen3-235b
revision: main
gpus_per_replica: 24
replicas: 1
args: "--block-size 32 --enable-expert-parallel --enable-reasoning --reasoning-parser deepseek_r1 --pipeline-parallel-size 6  --dtype bfloat16 --gpu-memory-utilization 0.9 --max-model-len 38912 --max-num-seqs 128"
wait_endpoint_s: 3600
env:
  HF_HOME: /path/to/hf_home/
image: /path/to/vllm.sif
backend:
  type: slurm
