model: Qwen/Qwen3-235B-A22B
revision: main
gpus_per_replica: 24
replicas: 1
vllm_args: "--block-size 32 --enable-expert-parallel --enable-reasoning --reasoning-parser deepseek_r1 --pipeline-parallel-size 6  --dtype bfloat16 --gpu-memory-utilization 0.9 --max-model-len 38912 --max-num-seqs 128"
lb_wait: 3600
hf_home: /leonardo_scratch/fast/iGen_train/shared_hf_cache/
vllm_image: /leonardo_work/iGen_train/fdambro1/images/vllm_0.9.1.sif